[package]
name = "cap-fs-ext"
version = "0.17.1-alpha.0"
description = "Extension traits for `Dir`, `File`, etc."
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["filesystem"]
categories = ["filesystem"]
repository = "https://github.com/bytecodealliance/cap-std"
edition = "2018"

[build-dependencies]
rustc_version = "0.4.0"

[dependencies]
arf-strings = { version = "0.4.0", optional = true }
cap-async-std = { path = "../cap-async-std", optional = true, version = "^0.17.1-alpha.0"}
cap-std = { path = "../cap-std", optional = true, version = "^0.17.1-alpha.0"}
cap-primitives = { path = "../cap-primitives", version = "^0.18.0"}
io-lifetimes = "0.3.0"
# Enable "unstable" for `spawn_blocking`.
async-std = { version = "1.10.0", features = ["attributes", "unstable"], optional = true }
async-trait = { version = "0.1.42", optional = true }

[features]
default = ["std"]
fs_utf8 = ["arf-strings", "cap-std/fs_utf8"]
std = ["cap-std"]
async_std = ["cap-async-std", "async-std", "io-lifetimes/async-std", "async-trait"]
async_std_fs_utf8 = ["cap-async-std/fs_utf8"]

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[dev-dependencies]
cap-tempfile = { path = "../cap-tempfile" }

[badges]
maintenance = { status = "actively-developed" }
