[package]
name = "cap-fs-ext"
version = "0.7.0"
description = "Extension traits for `Dir`, `File`, etc."
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["filesystem"]
categories = ["filesystem"]
repository = "https://github.com/bytecodealliance/cap-std"
edition = "2018"
readme = "README.md"

[dependencies]
arf-strings = { version = "0.3.0", optional = true }
cap-async-std = { path = "../cap-async-std", optional = true, version = "^0.7.1-alpha.0"}
cap-std = { path = "../cap-std", optional = true, version = "^0.7.1-alpha.0"}
cap-primitives = { path = "../cap-primitives", version = "^0.7.1-alpha.0"}

[features]
default = ["std"]
fs_utf8 = ["arf-strings"]
std = ["cap-std"]
async_std = ["cap-async-std"]
nightly = ["windows_by_handle"]
windows_by_handle = [] # https://github.com/rust-lang/rust/issues/63010

[badges]
maintenance = { status = "actively-developed" }
