[package]
name = "cap-std"
version = "0.19.0"
description = "Capability-based version of the Rust standard library"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["std", "api", "network", "file"]
categories = ["filesystem", "network-programming"]
repository = "https://github.com/bytecodealliance/cap-std"
edition = "2018"

[build-dependencies]
rustc_version = "0.4.0"

[dependencies]
arf-strings = { version = "0.4.0", optional = true }
cap-primitives = { path = "../cap-primitives", version = "^0.19.1-alpha.0"}
ipnet = "2.3.0"
unsafe-io = "0.9.1"
io-lifetimes = { version = "0.3.0", default-features = false }
camino = { version = "1.0.5", optional = true }

[target.'cfg(not(windows))'.dependencies]
rsix = "0.22.4"

[features]
default = []
fs_utf8 = ["arf-strings", "camino"]

[badges]
maintenance = { status = "actively-developed" }
