[package]
name = "cap-std"
version = "0.2.1-alpha.0"
description = "Capability-oriented version of the Rust standard library"
authors = ["Dan Gohman <dev@sunfishcode.online>", "Jakub Konka <kubkon@jakubkonka.com>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["std", "api", "network", "file"]
categories = ["filesystem", "network-programming"]
repository = "https://github.com/sunfishcode/cap-std"
edition = "2018"
readme = "README.md"

[dependencies]
arf-strings = { version = "0.1.2", optional = true }
cap-primitives = { path = "../cap-primitives", version = "^0.2.1-alpha.0", default-features = false }

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["no_racy_asserts"]
can_vector = [] # https://github.com/rust-lang/rust/issues/69941
fs_utf8 = ["arf-strings"]
nightly = [
    "cap-primitives/nightly",
    "with_options",
    "can_vector",
    "read_initializer",
    "write_all_vectored",
    "seek_convenience",
]
no_racy_asserts = ["cap-primitives/no_racy_asserts"]
read_initializer = [] # https://github.com/rust-lang/rust/issues/42788
seek_convenience = [] # https://github.com/rust-lang/rust/issues/59359
with_options = [] # https://github.com/rust-lang/rust/issues/65439
write_all_vectored = [] # https://github.com/rust-lang/rust/issues/70436
