[package]
name = "cap-async-std"
version = "0.13.0"
description = "Capability-oriented version of async-std"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["network", "file", "async", "future", "await"]
categories = ["filesystem", "network-programming", "asynchronous", "concurrency"]
repository = "https://github.com/bytecodealliance/cap-std"
edition = "2018"
readme = "README.md"

[dependencies]
arf-strings = { version = "0.3.0", optional = true }
async-std = { version = "1.8.0", features = ["attributes"] }
cap-primitives = { path = "../cap-primitives", version = "^0.13.0"}
unsafe-io = "0.3.0"

[features]
default = []
fs_utf8 = ["arf-strings"]

[badges]
maintenance = { status = "actively-developed" }
