[package]
name = "cap-async-std"
version = "0.16.4-alpha.0"
description = "Capability-based version of async-std"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["network", "file", "async", "future", "await"]
categories = ["filesystem", "network-programming", "asynchronous", "concurrency"]
repository = "https://github.com/bytecodealliance/cap-std"
edition = "2018"

[dependencies]
arf-strings = { version = "0.3.0", optional = true }
async-std = { version = "1.9.0", features = ["attributes"] }
cap-primitives = { path = "../cap-primitives", version = "^0.16.4-alpha.0"}
io-lifetimes = { version = "0.2.2", features = ["async-std"] }
ipnet = "2.3.0"
unsafe-io = { version = "0.7.0", features = ["async-std"] }

[target.'cfg(not(windows))'.dependencies]
posish = "0.16.6"

[features]
default = []
fs_utf8 = ["arf-strings"]

[badges]
maintenance = { status = "actively-developed" }
