[package]
name = "cap-async-std"
version = "0.5.0"
description = "Capability-oriented version of async-std"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["network", "file", "async", "future", "await"]
categories = ["filesystem", "network-programming", "asynchronous", "concurrency"]
repository = "https://github.com/bytecodealliance/cap-std"
edition = "2018"
readme = "README.md"

[dependencies]
arf-strings = { version = "0.3.0", optional = true }
async-std = { version = "1.6.5", features = ["attributes"] }
cap-primitives = { path = "../cap-primitives", version = "^0.5.1-alpha.0"}

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
can_vector = [] # https://github.com/rust-lang/rust/issues/69941
fs_utf8 = ["arf-strings"]
nightly = [
    "cap-primitives/nightly",
    "with_options",
    "can_vector",
    "read_initializer",
    "write_all_vectored",
    "seek_convenience",
]
read_initializer = [] # https://github.com/rust-lang/rust/issues/42788
seek_convenience = [] # https://github.com/rust-lang/rust/issues/59359
with_options = [] # https://github.com/rust-lang/rust/issues/65439
write_all_vectored = [] # https://github.com/rust-lang/rust/issues/70436
